-- Gracewell NEXUS ERD Schema for Supabase
-- Run this SQL in your Supabase SQL Editor

-- Cleanup legacy tables that conflict with ERD
DROP TABLE IF EXISTS attendance_issues CASCADE;
DROP TABLE IF EXISTS attendance_scans CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS salary CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Department
CREATE TABLE IF NOT EXISTS departments (
  department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  department_name VARCHAR(150) NOT NULL
);

-- Role
CREATE TABLE IF NOT EXISTS roles (
  role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR(100) NOT NULL,
  description VARCHAR(255)
);

-- Employee
CREATE TABLE IF NOT EXISTS employees (
  employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code VARCHAR(50) UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  birth_date DATE,
  permanent_address VARCHAR(255),
  contact_number VARCHAR(50),
  profile_image_url VARCHAR(255),
  email_address VARCHAR(150),
  email_verified_at TIMESTAMP,
  position VARCHAR(100),
  department_id INT REFERENCES departments(department_id),
  basic_salary NUMERIC(12,2),
  employment_type VARCHAR(50),
  record_status VARCHAR(50),
  hire_date DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User Account
CREATE TABLE IF NOT EXISTS user_accounts (
  user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  username VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role_id INT NOT NULL REFERENCES roles(role_id),
  account_status VARCHAR(50) DEFAULT 'ACTIVE',
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP
);

-- QR Code
CREATE TABLE IF NOT EXISTS qr_codes (
  qrcode_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  qr_value VARCHAR(255) NOT NULL,
  status VARCHAR(50) DEFAULT 'ACTIVE',
  date_issued DATE DEFAULT CURRENT_DATE,
  issued_by INT REFERENCES user_accounts(user_id),
  revoked_at TIMESTAMP,
  revoked_by INT REFERENCES user_accounts(user_id)
);

-- Attendance Scan
CREATE TABLE IF NOT EXISTS attendance_scans (
  scan_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  qrcode_id INT REFERENCES qr_codes(qrcode_id),
  scan_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  scan_type VARCHAR(50),
  scan_result VARCHAR(50),
  rejected_reason VARCHAR(255),
  recorded_by INT REFERENCES user_accounts(user_id)
);

-- Attendance
CREATE TABLE IF NOT EXISTS attendance (
  attendance_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  attendance_date DATE NOT NULL,
  check_out_date DATE,
  status VARCHAR(50),
  check_in_time TIME,
  check_out_time TIME,
  hours_worked NUMERIC(6,2),
  check_in_scan_id INT REFERENCES attendance_scans(scan_id),
  check_out_scan_id INT REFERENCES attendance_scans(scan_id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Attendance Issue
CREATE TABLE IF NOT EXISTS attendance_issues (
  issue_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_id INT NOT NULL REFERENCES attendance(attendance_id) ON DELETE CASCADE,
  issue_type VARCHAR(100),
  description VARCHAR(255),
  reported_by INT REFERENCES user_accounts(user_id),
  reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(50),
  resolved_by INT REFERENCES user_accounts(user_id),
  resolved_at TIMESTAMP,
  resolution_notes VARCHAR(255)
);

-- Salary Record
CREATE TABLE IF NOT EXISTS salary_records (
  salary_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
  pay_period_start DATE,
  pay_period_end DATE,
  salary_amount NUMERIC(12,2) NOT NULL,
  status VARCHAR(50) DEFAULT 'Pending',
  release_date DATE,
  last_updated_at TIMESTAMP,
  last_updated_by INT REFERENCES user_accounts(user_id)
);

-- Salary Receipt
CREATE TABLE IF NOT EXISTS salary_receipts (
  receipt_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  salary_id INT NOT NULL REFERENCES salary_records(salary_id) ON DELETE CASCADE,
  receipt_number VARCHAR(100),
  generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  generated_by INT REFERENCES user_accounts(user_id),
  notes VARCHAR(255)
);

-- Audit Log
CREATE TABLE IF NOT EXISTS audit_logs (
  log_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT REFERENCES user_accounts(user_id),
  action VARCHAR(100) NOT NULL,
  module VARCHAR(100),
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  notes VARCHAR(255)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_employees_employee_code ON employees(employee_code);
CREATE INDEX IF NOT EXISTS idx_employees_email ON employees(email_address);
CREATE INDEX IF NOT EXISTS idx_attendance_employee_date ON attendance(employee_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(attendance_date);
CREATE INDEX IF NOT EXISTS idx_salary_employee_id ON salary_records(employee_id);
CREATE INDEX IF NOT EXISTS idx_salary_status ON salary_records(status);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_logs(timestamp);

-- Enable Row Level Security (RLS)
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE qr_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE salary_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE salary_receipts ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Basic permissive policies (adjust for production)
DROP POLICY IF EXISTS "Enable read access for all departments" ON departments;
DROP POLICY IF EXISTS "Enable read access for all roles" ON roles;
DROP POLICY IF EXISTS "Enable read access for all employees" ON employees;
DROP POLICY IF EXISTS "Enable read access for all user_accounts" ON user_accounts;
DROP POLICY IF EXISTS "Enable read access for all qr_codes" ON qr_codes;
DROP POLICY IF EXISTS "Enable read access for all attendance_scans" ON attendance_scans;
DROP POLICY IF EXISTS "Enable read access for all attendance" ON attendance;
DROP POLICY IF EXISTS "Enable read access for all attendance_issues" ON attendance_issues;
DROP POLICY IF EXISTS "Enable read access for all salary_records" ON salary_records;
DROP POLICY IF EXISTS "Enable read access for all salary_receipts" ON salary_receipts;
DROP POLICY IF EXISTS "Enable read access for all audit_logs" ON audit_logs;

DROP POLICY IF EXISTS "Enable insert for authenticated departments" ON departments;
DROP POLICY IF EXISTS "Enable insert for authenticated roles" ON roles;
DROP POLICY IF EXISTS "Enable insert for authenticated employees" ON employees;
DROP POLICY IF EXISTS "Enable insert for authenticated user_accounts" ON user_accounts;
DROP POLICY IF EXISTS "Enable insert for authenticated qr_codes" ON qr_codes;
DROP POLICY IF EXISTS "Enable insert for authenticated attendance_scans" ON attendance_scans;
DROP POLICY IF EXISTS "Enable insert for authenticated attendance" ON attendance;
DROP POLICY IF EXISTS "Enable insert for authenticated attendance_issues" ON attendance_issues;
DROP POLICY IF EXISTS "Enable insert for authenticated salary_records" ON salary_records;
DROP POLICY IF EXISTS "Enable insert for authenticated salary_receipts" ON salary_receipts;
DROP POLICY IF EXISTS "Enable insert for authenticated audit_logs" ON audit_logs;

DROP POLICY IF EXISTS "Enable update for authenticated departments" ON departments;
DROP POLICY IF EXISTS "Enable update for authenticated roles" ON roles;
DROP POLICY IF EXISTS "Enable update for authenticated employees" ON employees;
DROP POLICY IF EXISTS "Enable update for authenticated user_accounts" ON user_accounts;
DROP POLICY IF EXISTS "Enable update for authenticated qr_codes" ON qr_codes;
DROP POLICY IF EXISTS "Enable update for authenticated attendance_scans" ON attendance_scans;
DROP POLICY IF EXISTS "Enable update for authenticated attendance" ON attendance;
DROP POLICY IF EXISTS "Enable update for authenticated attendance_issues" ON attendance_issues;
DROP POLICY IF EXISTS "Enable update for authenticated salary_records" ON salary_records;
DROP POLICY IF EXISTS "Enable update for authenticated salary_receipts" ON salary_receipts;
DROP POLICY IF EXISTS "Enable update for authenticated audit_logs" ON audit_logs;

CREATE POLICY "Enable read access for all departments" ON departments FOR SELECT USING (true);
CREATE POLICY "Enable read access for all roles" ON roles FOR SELECT USING (true);
CREATE POLICY "Enable read access for all employees" ON employees FOR SELECT USING (true);
CREATE POLICY "Enable read access for all user_accounts" ON user_accounts FOR SELECT USING (true);
CREATE POLICY "Enable read access for all qr_codes" ON qr_codes FOR SELECT USING (true);
CREATE POLICY "Enable read access for all attendance_scans" ON attendance_scans FOR SELECT USING (true);
CREATE POLICY "Enable read access for all attendance" ON attendance FOR SELECT USING (true);
CREATE POLICY "Enable read access for all attendance_issues" ON attendance_issues FOR SELECT USING (true);
CREATE POLICY "Enable read access for all salary_records" ON salary_records FOR SELECT USING (true);
CREATE POLICY "Enable read access for all salary_receipts" ON salary_receipts FOR SELECT USING (true);
CREATE POLICY "Enable read access for all audit_logs" ON audit_logs FOR SELECT USING (true);

CREATE POLICY "Enable insert for authenticated departments" ON departments FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated roles" ON roles FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated employees" ON employees FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated user_accounts" ON user_accounts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated qr_codes" ON qr_codes FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated attendance_scans" ON attendance_scans FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated attendance" ON attendance FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated attendance_issues" ON attendance_issues FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated salary_records" ON salary_records FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated salary_receipts" ON salary_receipts FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable insert for authenticated audit_logs" ON audit_logs FOR INSERT WITH CHECK (true);

CREATE POLICY "Enable update for authenticated departments" ON departments FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated roles" ON roles FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated employees" ON employees FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated user_accounts" ON user_accounts FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated qr_codes" ON qr_codes FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated attendance_scans" ON attendance_scans FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated attendance" ON attendance FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated attendance_issues" ON attendance_issues FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated salary_records" ON salary_records FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated salary_receipts" ON salary_receipts FOR UPDATE USING (true);
CREATE POLICY "Enable update for authenticated audit_logs" ON audit_logs FOR UPDATE USING (true);
